remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Felipe Alarcón Peña
description: Welcome to my webpage!

theme: jekyll-theme-minimal