# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome to my webpage!
email: falarcon@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  I am a Ph.D.(c) in Astronomy at the University of Michigan. my main research work is about the chemistry in planet-forming regions/disks using either a theoretical or 
  observational approach with  molecular tracers.
  
#twitter_username: username
github_username: Falarconp
minimal_mistakes_skin: neon
search: true
teaser: "/assets/images/as209.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/



include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Felipe Alarcón Peña"
  avatar : "/assets/images/felipe-alarcon.jpeg"
  bio    : "  I am a Ph.D.(c) in Astronomy at Umich working under the supervision of Dr. Edwin(Ted) Bergin. I am mostly interested in the chemistry of planet formation processes."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Falarconp/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:falarcon@umich.edu"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Falarconp/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:falarcon@umich.edu"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  
 # Analytics

google_analytics: G-HFD2M3F8SV
google_analytics: 'G-HFD2M3F8SV'

